### ISSUE TITLE
Support for cssNext nesting

### ISSUE THREAD

**Issue by jacksaunders** [Connormiha/jest-css-modules-transform#4]
Hey, I am [CSS next](http://cssnext.io/) in my css modules in a react project, and specifically within that i am using the [nesting feature](http://cssnext.io/features/#nesting). 

example
```css
.MyAccount {
    position: relative;

    & .sidebar {
        float: left;
    }
}

```

This preprocessor doesn't seem to be able to handle that as when i debug in enzyme it processes the `.MyAccount` class ok but returns `undefined` for sidebar

```jsx
<div className="MyAccount">
          <div className={[undefined]}>
               Content
          </div>
</div>
```

Thanks
