### ISSUE TITLE
Global style sheet with only :root selector seems to be excluded

### ISSUE THREAD

**Issue by Poimen** [Connormiha/jest-css-modules-transform#42]
Hi,

Our project has a number of global stylesheets that contain only css variables. The variables appear not to be injected into the document when there is no actual css class in the css file.

For example, our test does:
```jsx
// Beautiful.spec.js
import React from "react";
import './index.css';
import Beautiful from "./Beautiful";
// ... more test imports

it("should have no visual regressions", async () => {
  const { getByTestId } = render(<Beautiful />);
  fireEvent.click(getByTestId("beautiful-button"));

  // expect(await generateImage()).toMatchImageSnapshot();  <-- this is what would normally take the screenshot, but for now, console log below
  console.dir(document.head.innerHTML);
});
```

The `index.css` above is the global stylesheet. It contains:
```css
/* index.css */
:root {
    --some-var: blue;
}
```

The component pulls this in via an import `import './beautiful.css';` which in turn uses the variable:
```css
/* beautiful.css */
.button {
  background: var(--some-var);
}
```

The output from the console log is:
```html
<style>.button {
        background: var(--some-var);
      }</style>
```

So the button component import it's css fine, but `index.css` has gone missing.

If I update `index.css` to:
```css
/* index.css */
:root {
    --some-var: blue;
}
.stub {}
```

Then the console log becomes:
```html
/* index.css */
 <style>:root {
          --some-var: blue;
      }
      .stub {}</style><style>.button {
        background: var(--some-var);
      }</style>
```

Now the `index.css` values appear in the document head. I can even comment out the stub class:
```css
/* index.css */
:root {
    --some-var: blue;
}
/* .stub {} */
```

And styles appear correctly in the document head:
```html
<style>:root {
          --some-var: blue;
      }
      /* .stub {} */</style><style>.button {
        background: var(--some-var);
      }</style>
```

Am I including global styles correctly? Or is there something rejecting the css variables?

Thanks.
