### ISSUE TITLE
[Feature Request] Generate scoped className

### ISSUE THREAD

**Issue by ghostd** [Connormiha/jest-css-modules-transform#54]
For now, if we want to test nested components, there can be some class name conflicts.

```jsx
// Foo.jsx
import Bar from './Bar';
import styles from './foo.module.scss';

function Foo() {
  return (
    <div className={styles.show}>
      <Bar />
    </div>
  );
}

export default Foo;
```

```jsx
// Bar.jsx
import styles from './bar.module.scss';

function Bar() {
  return <p className={styles.show}>bar content</p>;
}

export default Bar;
```

```scss
// foo.module.scss
.show {
  display: block;
}
```

```scss
// bar.module.scss
.show {
  display: flex;
}
```

```js
// jest-css-modules-transform-config.js
const path = require('path');

module.exports = {
  sassConfig: {
    includePaths: [path.resolve(__dirname, 'src')],
  },
  injectIntoDOM: true,
};

```

The injected CSS are conflicting:
```css
.show {display: flex;}
.show {display: block;}
```
```html
    <body>
      <div>
        <div
          class="show"
        >
          <p
            class="show"
          >
            bar content
          </p>
        </div>
      </div>
    </body>
```

It would be a big improvement if this jest transformer would generate something like the webpack loaders (Foo__show_SomeHash, Bar__show_OtherHash)
